/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latihan;
import latihan.MyClass;
import java.util.Scanner;

public class App {
    public static void mainMenu() {
        int pilihan, angka1,angka2,x,  y;
        Scanner scan = new Scanner(System.in);
      
        System.out.println("[1] Java 8 Examples - Functional Java");
        System.out.println("[2] Exit");
        System.out.println("Masukkan pilihan Anda : ");
        pilihan = scan.nextInt();
        switch (pilihan) {
            
            case 1:
            MyClass class1 = new MyClass();
            // class1.multiply();
            mainMenu();
            break;
            default:
                System.out.println("Angka yang Anda masukkan tidak valid");
                mainMenu();
                break;
        }

    }    public static void main(String[] args) {
        mainMenu();
    }
}
